CREATE TABLE IF NOT EXISTS "ARCHIVO_COMPENSACION" (
    "ID_ARCHIVO_COMPENSACION" UUID PRIMARY KEY,
    "ID_LOTE" UUID NOT NULL UNIQUE,
    "ID_CORRELACION" UUID NOT NULL,
    "NOMBRE_ARCHIVO" VARCHAR(160) NOT NULL,
    "RUTA_RELATIVA" VARCHAR(240) NOT NULL,
    "ESTADO" VARCHAR(40) NOT NULL,
    "TOTAL_LINEAS" INTEGER NOT NULL,
    "MONTO_TOTAL" NUMERIC(18, 2) NOT NULL,
    "MONEDA" VARCHAR(3) NOT NULL,
    "FECHA_CREACION" TIMESTAMPTZ NOT NULL,
    "FECHA_ACTUALIZACION" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "LINEA_ARCHIVO_COMPENSACION" (
    "ID_LINEA_ARCHIVO_COMPENSACION" UUID PRIMARY KEY,
    "ID_ARCHIVO_COMPENSACION" UUID NOT NULL,
    "ID_EVENTO_ORIGEN" UUID NOT NULL,
    "ID_LOTE" UUID NOT NULL,
    "ID_LINEA" UUID NOT NULL UNIQUE,
    "ID_CORRELACION" UUID NOT NULL,
    "NUMERO_SECUENCIA" INTEGER,
    "RUC_EMPRESA" VARCHAR(20),
    "NUMERO_CUENTA_MATRIZ" VARCHAR(40),
    "ID_FONDEO_CORE" VARCHAR(80),
    "IDENTIFICACION_BENEFICIARIO" VARCHAR(30) NOT NULL,
    "NOMBRE_BENEFICIARIO" VARCHAR(120) NOT NULL,
    "NUMERO_CUENTA_DESTINO" VARCHAR(40) NOT NULL,
    "CODIGO_ENRUTAMIENTO" VARCHAR(10) NOT NULL,
    "NOMBRE_INSTITUCION_DESTINO" VARCHAR(120),
    "MONTO" NUMERIC(18, 2) NOT NULL,
    "MONEDA" VARCHAR(3) NOT NULL,
    "REFERENCIA" VARCHAR(140),
    "EMAIL_NOTIFICACION" VARCHAR(120),
    "ESTADO" VARCHAR(40) NOT NULL,
    "COBRABLE" BOOLEAN NOT NULL,
    "CODIGO_RECHAZO" VARCHAR(80),
    "MOTIVO_RECHAZO" VARCHAR(500),
    "FECHA_RECEPCION" TIMESTAMPTZ NOT NULL,
    "FECHA_INCLUSION" TIMESTAMPTZ,
    "FECHA_ACTUALIZACION" TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS "IDX_ARCHIVO_COMPENSACION_LOTE"
    ON "ARCHIVO_COMPENSACION" ("ID_LOTE");

CREATE INDEX IF NOT EXISTS "IDX_LINEA_COMPENSACION_LOTE"
    ON "LINEA_ARCHIVO_COMPENSACION" ("ID_LOTE");

CREATE INDEX IF NOT EXISTS "IDX_LINEA_COMPENSACION_ARCHIVO"
    ON "LINEA_ARCHIVO_COMPENSACION" ("ID_ARCHIVO_COMPENSACION");

CREATE INDEX IF NOT EXISTS "IDX_LINEA_COMPENSACION_ESTADO"
    ON "LINEA_ARCHIVO_COMPENSACION" ("ESTADO");
