CREATE TABLE IF NOT EXISTS "OBSERVACION_LINEA_LOTE" (
    "ID_OBSERVACION_LINEA_LOTE" UUID PRIMARY KEY,
    "ID_EVENTO_ORIGEN" UUID NOT NULL,
    "ID_LOTE" UUID NOT NULL,
    "ID_LINEA" UUID NOT NULL UNIQUE,
    "ID_CORRELACION" UUID NOT NULL,
    "NUMERO_SECUENCIA" INTEGER,
    "RUC_EMPRESA" VARCHAR(20),
    "NUMERO_CUENTA_MATRIZ" VARCHAR(40),
    "ID_FONDEO_CORE" VARCHAR(80),
    "MONTO" NUMERIC(18, 2) NOT NULL,
    "MONEDA" VARCHAR(3) NOT NULL,
    "TOTAL_LINEAS_LOTE" INTEGER,
    "MONTO_CONTROL_LOTE" NUMERIC(18, 2),
    "FECHA_OBSERVACION" TIMESTAMPTZ NOT NULL,
    "FECHA_ACTUALIZACION" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "RESULTADO_PROCESAMIENTO_LINEA" (
    "ID_RESULTADO_PROCESAMIENTO_LINEA" UUID PRIMARY KEY,
    "ID_EVENTO_ORIGEN" UUID NOT NULL,
    "ID_LOTE" UUID NOT NULL,
    "ID_LINEA" UUID NOT NULL UNIQUE,
    "ID_CORRELACION" UUID NOT NULL,
    "ESTADO_FINAL" VARCHAR(40) NOT NULL,
    "COBRABLE" BOOLEAN NOT NULL,
    "MONTO" NUMERIC(18, 2) NOT NULL,
    "MONEDA" VARCHAR(3) NOT NULL,
    "FUENTE_RESULTADO" VARCHAR(60) NOT NULL,
    "ID_TRANSACCION_CORE" VARCHAR(80),
    "ID_ARCHIVO_COMPENSACION" UUID,
    "NOMBRE_ARCHIVO_COMPENSACION" VARCHAR(160),
    "CODIGO_RECHAZO" VARCHAR(80),
    "MOTIVO_RECHAZO" VARCHAR(500),
    "EMAIL_NOTIFICACION" VARCHAR(120),
    "FECHA_RECEPCION" TIMESTAMPTZ NOT NULL,
    "FECHA_ACTUALIZACION" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS "RESUMEN_PROCESAMIENTO_LOTE" (
    "ID_RESUMEN_PROCESAMIENTO_LOTE" UUID PRIMARY KEY,
    "ID_LOTE" UUID NOT NULL UNIQUE,
    "ID_CORRELACION" UUID NOT NULL,
    "RUC_EMPRESA" VARCHAR(20),
    "NUMERO_CUENTA_MATRIZ" VARCHAR(40),
    "ID_FONDEO_CORE" VARCHAR(80),
    "TOTAL_LINEAS_ESPERADAS" INTEGER,
    "LINEAS_OBSERVADAS" INTEGER NOT NULL,
    "LINEAS_RESULTADO_FINAL" INTEGER NOT NULL,
    "LINEAS_ON_US_ACREDITADAS" INTEGER NOT NULL,
    "LINEAS_OFF_US_INCLUIDAS" INTEGER NOT NULL,
    "LINEAS_RECHAZADAS" INTEGER NOT NULL,
    "LINEAS_FALLIDAS" INTEGER NOT NULL,
    "LINEAS_COBRABLES" INTEGER NOT NULL,
    "MONTO_CONTROL" NUMERIC(18, 2),
    "MONTO_PROCESADO" NUMERIC(18, 2) NOT NULL,
    "MONTO_REMANENTE" NUMERIC(18, 2),
    "MONEDA" VARCHAR(3) NOT NULL,
    "ESTADO" VARCHAR(40) NOT NULL,
    "EVENTO_COMPLETADO_PUBLICADO" BOOLEAN NOT NULL,
    "ID_EVENTO_COMPLETADO" UUID,
    "FECHA_PRIMERA_OBSERVACION" TIMESTAMPTZ NOT NULL,
    "FECHA_FINALIZACION" TIMESTAMPTZ,
    "FECHA_ACTUALIZACION" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "RESUMEN_PROCESAMIENTO_LOTE"
    ADD COLUMN IF NOT EXISTS "RUC_EMPRESA" VARCHAR(20);

ALTER TABLE "RESUMEN_PROCESAMIENTO_LOTE"
    ADD COLUMN IF NOT EXISTS "NUMERO_CUENTA_MATRIZ" VARCHAR(40);

ALTER TABLE "RESUMEN_PROCESAMIENTO_LOTE"
    ADD COLUMN IF NOT EXISTS "ID_FONDEO_CORE" VARCHAR(80);

CREATE INDEX IF NOT EXISTS "IDX_OBSERVACION_LINEA_LOTE"
    ON "OBSERVACION_LINEA_LOTE" ("ID_LOTE");

CREATE INDEX IF NOT EXISTS "IDX_RESULTADO_LINEA_LOTE"
    ON "RESULTADO_PROCESAMIENTO_LINEA" ("ID_LOTE");

CREATE INDEX IF NOT EXISTS "IDX_RESULTADO_LINEA_ESTADO"
    ON "RESULTADO_PROCESAMIENTO_LINEA" ("ESTADO_FINAL");

CREATE INDEX IF NOT EXISTS "IDX_RESUMEN_PROCESAMIENTO_LOTE"
    ON "RESUMEN_PROCESAMIENTO_LOTE" ("ID_LOTE");
